project:
  type: website
  output-dir: ../docs

website:
  title: "SSG - HS Forensics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: example1.qmd
        text: Example 1
      - href: https://github.com/vcu-ssg/ssg-hs-forensics-app
        text: Repository
      - href: ../forensics-ui/cell-gallery/gallery.qmd
        text: "Gallery"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
