project:
  type: website
  resources:
    - "lesson-1/assets/*.mp4"
  # create empty directory for Docker to store user images in
  post-render: mkdir -p _site/cell-gallery/assets/user-images

website:
  title: "FORENSICS-UI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: lesson-1/index.qmd
        text: "Lesson 1: Important Cells in Forensics"
      - href: upload/upload.qmd
        text: "Upload Image"
      - href: cell-gallery/gallery.qmd
        text: "Gallery"

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true



