
services:
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    expose:
      - "8000"
    restart: always
    volumes:
      - ../forensics-ui/_site/cell-gallery/assets/user-images:/cell-gallery/assets/user-images


  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      # bind mounts
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../forensics-ui/_site:/usr/share/nginx/html:ro
    depends_on:
      - fastapi
    restart: always